---
name: IO-Callback
version: 1.02
author:
  - 'Dave Taylor <dave.taylor.cpan@gmail.com>'
abstract: Emulate file interface for a code reference
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Errno: 0
  IO::String: 0
build_requires:
  Fatal: 0
  Fcntl: 0
  File::Slurp: 0
  File::Temp: 0
  IO::Handle: 0
  Test::Exception: 0
  Test::More: 0
  Test::NoWarnings: 0
provides:
  IO::Callback:
    file: lib/IO/Callback.pm
    version: 1.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
